#!/bin/sh
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
set -e

PACKAGE="nvmesh-client"
VERSION="3.4.0"

case "$1" in
    remove|upgrade|deconfigure)
        if which dkms > /dev/null 2>&1; then
            dkms remove "${PACKAGE}/${VERSION}" --all 2>/dev/null || true
        fi
        ;;
esac

#DEBHELPER#
